// Code generated by orlop-gen. DO NOT EDIT.

package v1

import (
	_ "embed"

	"github.com/openshift-online/gecko/orlop/pkg/apiserver/types"
)

var (
	// ClusterSchemaYAML contains the OpenAPI v3 schema for Cluster.
	//go:embed .schemas/cluster_schema.yaml
	ClusterSchemaYAML string

	// NodePoolSchemaYAML contains the OpenAPI v3 schema for NodePool.
	//go:embed .schemas/nodepool_schema.yaml
	NodePoolSchemaYAML string

	// PlatformRoleBindingSchemaYAML contains the OpenAPI v3 schema for PlatformRoleBinding.
	//go:embed .schemas/platformrolebinding_schema.yaml
	PlatformRoleBindingSchemaYAML string

	// RoleBindingSchemaYAML contains the OpenAPI v3 schema for RoleBinding.
	//go:embed .schemas/rolebinding_schema.yaml
	RoleBindingSchemaYAML string

)

// ClusterResourceInfo describes the Cluster resource type.
var ClusterResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("Cluster"),
	Plural:     "clusters",
	Singular:   "cluster",
	Namespaced: true,
	SchemaYAML: ClusterSchemaYAML,
}

// NodePoolResourceInfo describes the NodePool resource type.
var NodePoolResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("NodePool"),
	Plural:     "nodepools",
	Singular:   "nodepool",
	Namespaced: true,
	SchemaYAML: NodePoolSchemaYAML,
}

// PlatformRoleBindingResourceInfo describes the PlatformRoleBinding resource type.
var PlatformRoleBindingResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("PlatformRoleBinding"),
	Plural:     "platformrolebindings",
	Singular:   "platformrolebinding",
	Namespaced: false,
	SchemaYAML: PlatformRoleBindingSchemaYAML,
}

// RoleBindingResourceInfo describes the RoleBinding resource type.
var RoleBindingResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("RoleBinding"),
	Plural:     "rolebindings",
	Singular:   "rolebinding",
	Namespaced: true,
	SchemaYAML: RoleBindingSchemaYAML,
}

// GetResourceInfos returns ResourceInfo definitions for all types in this package.
// This can be used to configure an API server with these resources.
func GetResourceInfos() []types.ResourceInfo {
	return []types.ResourceInfo{
		ClusterResourceInfo,
		NodePoolResourceInfo,
		PlatformRoleBindingResourceInfo,
		RoleBindingResourceInfo,
	}
}
