package v1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// Cluster enables declarative management of OpenShift Clusters on GCP.
// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Namespaced
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Available",type=string,JSONPath=`.status.conditions[?(@.type=="HostedClusterAvailable")].status`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
type Cluster struct {
	metav1.TypeMeta `json:",inline"`
	// metadata is the standard object metadata.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// spec defines the desired behavior of the Cluster.

	// +required
	Spec ClusterSpec `json:"spec,omitempty"`

	// status is the most recently observed status of the Cluster.

	// +optional
	Status ClusterStatus `json:"status,omitempty"`
}

// ClusterList is a list of Clusters.
// +kubebuilder:object:root=true
type ClusterList struct {
	metav1.TypeMeta `json:",inline"`
	// metadata is the standard list metadata.
	// +optional
	metav1.ListMeta `json:"metadata,omitempty"`

	// items is the list of Clusters.

	Items []Cluster `json:"items"`
}

// ClusterSpec is defines the Cluster behavior.
type ClusterSpec struct {

	// TODO: Do we want to generate this id when not set by the user?
	// infraID is a globally unique identifier for the cluster.
	// It must consist of lowercase alphanumeric characters and hyphens ('-') only, and start and end with an alphanumeric character.
	// It must be no more than 253 characters in length.
	// This identifier will be used to associate various cloud resources with the Cluster and its associated NodePools.
	// If a value is not specified, a random infraID will be generated and set by the controller.
	// Once set, this value is immutable.
	//

	// +kubebuilder:validation:XValidation:rule="self.matches('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$')",message="infraID must consist of lowercase alphanumeric characters or '-', start and end with an alphanumeric character, and be between 1 and 253 characters"
	// +kubebuilder:validation:XValidation:rule=`oldSelf == "" || self == oldSelf`, message="infraID is immutable"
	// +kubebuilder:validation:MaxLength=253
	// +kubebuilder:validation:MinLength=1
	// +optional
	// +example="infra-xyz"
	InfraID string `json:"infraID,omitempty"`

	// issuerURL is an OIDC issuer URL which will be used as the issuer in all
	// ServiceAccount tokens generated by the control plane API server via --service-account-issuer kube api server flag.
	// https://k8s-docs.netlify.app/en/docs/reference/command-line-tools-reference/kube-apiserver/
	// https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#serviceaccount-token-volume-projection
	// The default value is kubernetes.default.svc, which only works for in-cluster
	// validation.
	// TODO: GCP specific documentation
	//

	// +optional
	// +default="https://kubernetes.default.svc"
	// +kubebuilder:validation:MaxLength=255
	// +kubebuilder:validation:XValidation:rule="self == oldSelf", message="issuerURL is immutable"
	// +kubebuilder:validation:XValidation:rule="isURL(self)",message="issuerURL must be a valid absolute URL"
	IssuerURL string `json:"issuerURL,omitempty"`

	// platform specifies the underlying infrastructure provider for the cluster
	// and is used to configure platform specific behavior.

	// +required
	Platform ClusterPlatformSpec `json:"platform"`

	// release specifies what OpenShift release to use for the cluster.

	// +required
	Release ReleaseSpec `json:"release"`

	// +required
	Networking NetworkingSpec `json:"networking"`

	// +optional
	DNS *DNSSpec `json:"dns,omitempty"`
}

// ClusterPlatformSpec defines the behavor of the infrastructure provider.
// TODO: We only support GCP, should we flatten this structure?
type ClusterPlatformSpec struct {
	// type specifies the infrastrucutre provider. Must be "GCP".

	// +required
	// +kubebuilder:validation:Enum=GCP
	Type string `json:"type"`
	// gcp specifies the behavior of the Google Cloud Platform - GCP
	// infrastructure provider.

	// +required
	GCP *GCPClusterPlatform `json:"gcp,omitempty"`
}

// GCPClusterPlatform defines the behavor of the GCP infrastructure provider.
type GCPClusterPlatform struct {
	// project is the GCP project ID.
	// A valid project ID must satisfy the following rules:
	//   length: Must be between 6 and 30 characters, inclusive
	//   characters: Only lowercase letters (`a-z`), digits (`0-9`), and hyphens (`-`) are allowed
	//   start and end: Must begin with a lowercase letter and must not end with a hyphen
	//   valid examples: "my-project", "my-project-1", "my-project-123".
	// See https://cloud.google.com/resource-manager/docs/creating-managing-projects for project ID naming rules.
	//

	// +kubebuilder:validation:MinLength=6
	// +kubebuilder:validation:MaxLength=30
	// +kubebuilder:validation:XValidation:rule="self.matches('^[a-z][a-z0-9-]{4,28}[a-z0-9]$')",message="project must start with a lowercase letter, contain only lowercase letters, digits, or hyphens, and end with a letter or digit"
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Project is immutable"
	// +required
	// +example="my-project"
	ProjectID string `json:"projectID,omitempty"`

	// region is the GCP region in which the cluster resides (e.g., us-central1, europe-west2).
	// Must start with lowercase letters, contain exactly one hyphen, and end with digits.
	// For a full list of valid regions, see: https://cloud.google.com/compute/docs/regions-zones.
	//

	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:XValidation:rule="self.matches('^[a-z]+-[a-z]+[0-9]+$')",message="region must be a valid GCP region (e.g., us-central1, europe-west2)"
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Region is immutable"
	// +required
	// +example="us-central1"
	Region string `json:"region,omitempty"`

	// network is the VPC network name.
	// TODO: Rename to NetworkName/NetworkID or even VPCNetworkName?
	//

	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Network is immutable"
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:XValidation:rule="self.matches('^[a-z]+-[a-z]+[0-9]+$')",message="network must be a valid RFC 1035 label (e.g., my-pvc-network)"
	// +required
	// +example="my-vpc-network"
	Network string `json:"network,omitempty"`

	// subnet is the subnet name for Private Service Connect endpoints.
	// TODO: maps to PrivateServiceConnectSubnet in HyperShift, rename?
	//

	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Subnet is immutable"
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:XValidation:rule="self.matches('^[a-z]+-[a-z]+[0-9]+$')",message="subnet must be a valid RFC 1035 label (e.g., my-subnet)"
	// +required
	// +example="my-subnet"
	Subnet string `json:"subnet,omitempty"`

	// endpointAccess controls API endpoint accessibility for the HostedControlPlane.
	// Allowed values: "Private", "PublicAndPrivate". Defaults to "Private".

	// +optional
	// +default="Private"
	// +kubebuilder:validation:Enum=PublicAndPrivate;Private
	EndpointAccess string `json:"endpointAccess,omitempty"`

	// workloadIdentity configures Workload Identity Federation for the cluster.
	// This enables secure, short-lived token-based authentication without storing
	// long-term service account keys. These fields are immutable after cluster creation
	// to prevent breaking the authentication chain.
	//
	// Prerequisites for WIF setup:
	//   - Workload Identity Pool and Provider must exist in the GCP project
	//   - Provider must be configured with audience mapping for OpenShift SA tokens
	//   - Target Google Service Account must have roles/iam.workloadIdentityUser
	//     granted to the workload pool principal (e.g., principal://iam.googleapis.com/projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/subject/system:serviceaccount:kube-system:capi-gcp-controller-manager)
	//   - Attribute mappings on the provider should include google.subject for token subject verification
	//

	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="WorkloadIdentity is immutable"
	// +required
	WorkloadIdentity WorkloadIdentitySpec `json:"workloadIdentity"`

	// resourceLabels are applied to all GCP resources created for the cluster.
	// Labels are key-value pairs used for organizing and managing GCP resources.
	// Changes to this field will be propagated in-place to GCP resources where supported.
	// GCP supports a maximum of 64 labels per resource. HyperShift reserves approximately 4 labels for system use.
	// For GCP labeling guidance, see https://cloud.google.com/compute/docs/labeling-resources
	//

	// +listType=map
	// +listMapKey=key
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=60
	ResourceLabels []GCPResourceLabel `json:"resourceLabels,omitempty"`
}

// WorkloadIdentitySpec defines Workload Identity Federation for the cluster.
type WorkloadIdentitySpec struct {
	// poolID is the workload identity pool identifier within the project.
	// This pool is used to manage external identity mappings.
	// Must be 4-32 characters and start with a lowercase letter.
	// Allowed characters: lowercase letters (a-z), digits (0-9), hyphens (-).
	// Cannot start or end with a hyphen.
	// The prefix "gcp-" is reserved by Google and cannot be used.
	// See https://cloud.google.com/iam/docs/manage-workload-identity-pools-providers for naming rules.
	//
	// This is a user-provided value referencing a pre-created Workload Identity Pool.
	// Typically obtained from the output of `hypershift infra create gcp` which creates
	// the WIF infrastructure and generates appropriate pool IDs.
	//

	// +required
	// +kubebuilder:validation:MinLength=4
	// +kubebuilder:validation:MaxLength=32
	// +kubebuilder:validation:XValidation:rule="self.matches('^[a-z][a-z0-9-]{2,30}[a-z0-9]$')",message="poolID must start with a lowercase letter, contain only lowercase letters, digits, or hyphens, and end with a letter or digit"
	// +kubebuilder:validation:XValidation:rule="!self.startsWith('gcp-')", message="Pool ID cannot start with reserved prefix 'gcp-'"
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Pool ID is immutable"
	PoolID string `json:"poolID,omitempty"`

	// projectNumber is the numeric GCP project identifier for WIF configuration.
	// This differs from the project ID and is required for workload identity pools.
	// Must be a numeric string representing the GCP project number.
	// See https://cloud.google.com/resource-manager/docs/creating-managing-projects for project number details.
	//
	// This is a user-provided value obtained from GCP (found in GCP Console or via `gcloud projects describe PROJECT_ID`).
	// Also available in the output of `hypershift infra create gcp`.
	//

	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=25
	// +kubebuilder:validation:XValidation:rule="self.matches('^[0-9]+$')",message="projectNumber must contain only digits"
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Project number is immutable"
	ProjectNumber string `json:"projectNumber,omitempty"`

	// providerID is the workload identity provider identifier within the pool.
	// This provider handles the token exchange between external and GCP identities.
	// Must be 4-32 characters and start with a lowercase letter.
	// Allowed characters: lowercase letters (a-z), digits (0-9), hyphens (-).
	// Cannot start or end with a hyphen.
	// The prefix "gcp-" is reserved by Google and cannot be used.
	// See https://cloud.google.com/iam/docs/manage-workload-identity-pools-providers for naming rules.
	//
	// This is a user-provided value referencing a pre-created OIDC Provider within the WIF Pool.
	// Typically obtained from the output of `hypershift infra create gcp`.
	//

	// +required
	// +kubebuilder:validation:MinLength=4
	// +kubebuilder:validation:MaxLength=32
	// +kubebuilder:validation:XValidation:rule="self.matches('^[a-z][a-z0-9-]{2,30}[a-z0-9]$')",message="providerID must start with a lowercase letter, contain only lowercase letters, digits, or hyphens, and end with a letter or digit"
	// +kubebuilder:validation:XValidation:rule="!self.startsWith('gcp-')", message="Provider ID cannot start with reserved prefix 'gcp-'"
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Provider ID is immutable"
	ProviderID string `json:"providerID,omitempty"`

	// serviceAccountsEmails contains email addresses of various Google Service Accounts
	// required to enable integrations for different controllers and operators.
	// This follows the AWS pattern of having different roles for different purposes.
	//

	// +required
	ServiceAccountsRef *ServiceAccountsRef `json:"serviceAccountsRef,omitempty"`
}

type ServiceAccountsRef struct {
	// nodePool is the Google Service Account email for CAPG controllers
	// that manage NodePool infrastructure (VMs, networks, disks, etc.).
	// This GSA requires the following IAM roles:
	// - roles/compute.instanceAdmin.v1 (Compute Instance Admin v1)
	// - roles/compute.networkAdmin (Compute Network Admin)
	// - roles/iam.serviceAccountUser (Service Account User - to attach service accounts to VMs)
	// See cmd/infra/gcp/iam-bindings.json for the authoritative role definitions.
	// Format: service-account-name@project-id.iam.gserviceaccount.com
	//
	// This is a user-provided value referencing a pre-created Google Service Account.
	// Typically obtained from the output of `hypershift infra create gcp` which creates
	// the required service accounts with appropriate IAM roles and WIF bindings.
	//

	// +required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="NodePoolEmail is immutable"
	NodePoolEmail string `json:"nodePoolEmail,omitempty"`

	// controlPlane is the Google Service Account email for the Control Plane Operator
	// that manages control plane infrastructure and resources.
	// This GSA requires the following IAM roles:
	// - roles/dns.admin (DNS Admin - for managing DNS records)
	// - roles/compute.networkAdmin (Compute Network Admin - for network management)
	// - roles/compute.viewer (Compute Viewer - for CCM to read instance metadata)
	// See cmd/infra/gcp/iam-bindings.json for the authoritative role definitions.
	// Format: service-account-name@project-id.iam.gserviceaccount.com
	//
	// This is a user-provided value referencing a pre-created Google Service Account.
	// Typically obtained from the output of `hypershift infra create gcp` which creates
	// the required service accounts with appropriate IAM roles and WIF bindings.
	//

	// +required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="ControlPlaneEmail is immutable"
	ControlPlaneEmail string `json:"controlPlaneEmail,omitempty"`

	// cloudController is the Google Service Account email for the Cloud Controller Manager
	// that manages LoadBalancer services and node lifecycle in the hosted cluster.
	// This GSA requires the following IAM roles:
	// - roles/compute.loadBalancerAdmin (Load Balancer Admin - for provisioning GCP load balancers)
	// - roles/compute.securityAdmin (Security Admin - for managing firewall rules)
	// - roles/compute.viewer (Compute Viewer - for reading instance metadata for node management)
	// See cmd/infra/gcp/iam-bindings.json for the authoritative role definitions.
	// Format: service-account-name@project-id.iam.gserviceaccount.com
	//
	// This is a user-provided value referencing a pre-created Google Service Account.
	// Typically obtained from the output of `hypershift infra create gcp` which creates
	// the required service accounts with appropriate IAM roles and WIF bindings.
	//

	// +required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="CloudControllerEmail is immutable"
	CloudControllerEmail string `json:"cloudControllerEmail,omitempty"`

	// storage is the Google Service Account email for the GCP PD CSI Driver
	// that manages Persistent Disk storage operations (create, attach, delete volumes).
	// This GSA requires the following IAM roles:
	// - roles/compute.storageAdmin (Compute Storage Admin - for managing persistent disks)
	// - roles/compute.instanceAdmin.v1 (Compute Instance Admin - for attaching disks to VMs)
	// - roles/iam.serviceAccountUser (Service Account User - for impersonation)
	// - roles/resourcemanager.tagUser (Tag User - for applying resource tags to disks)
	// See cmd/infra/gcp/iam-bindings.json for the authoritative role definitions.
	// Format: service-account-name@project-id.iam.gserviceaccount.com
	//
	// This is a user-provided value referencing a pre-created Google Service Account.
	// Typically obtained from the output of `hypershift infra create gcp` which creates
	// the required service accounts with appropriate IAM roles and WIF bindings.
	//

	// +required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="StorageEmail is immutable"
	StorageEmail string `json:"storageEmail,omitempty"`

	// imageRegistry is the Google Service Account email for the Image Registry Operator
	// that manages GCS storage for the internal container image registry.
	// This GSA requires the following IAM roles:
	// - roles/storage.admin (Storage Admin - for creating and managing GCS buckets and objects)
	// See cmd/infra/gcp/iam-bindings.json for the authoritative role definitions.
	// Format: service-account-name@project-id.iam.gserviceaccount.com
	//
	// This is a user-provided value referencing a pre-created Google Service Account.
	// Typically obtained from the output of `hypershift infra create gcp` which creates
	// the required service accounts with appropriate IAM roles and WIF bindings.
	//

	// +required
	// +immutable
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="ImageRegistryEmail is immutable"
	ImageRegistryEmail string `json:"imageRegistryEmail,omitempty"`

	// network is the Google Service Account email for the Cloud Network Config Controller
	// that manages cloud-level network configurations (egress IPs, subnets).
	// This GSA requires the following IAM roles:
	// - roles/compute.instanceAdmin.v1 (Compute Instance Admin - for managing network interfaces)
	// - roles/compute.networkUser (Compute Network User - for using subnets)
	// See cmd/infra/gcp/iam-bindings.json for the authoritative role definitions.
	// Format: service-account-name@project-id.iam.gserviceaccount.com
	//
	// This is a user-provided value referencing a pre-created Google Service Account.
	// Typically obtained from the output of `hypershift infra create gcp` which creates
	// the required service accounts with appropriate IAM roles and WIF bindings.
	//

	// +required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="NetworkEmail is immutable"
	NetworkEmail string `json:"networkEmail,omitempty"`
}

// GCPResourceLabel is a label applied to GCP resources created for the cluster.
type GCPResourceLabel struct {

	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=63
	Key string `json:"key"`

	// +optional
	// +kubebuilder:validation:MaxLength=63
	Value string `json:"value,omitempty"`
}

// ReleaseSpec defines the target OCP release version.
// The version-resolution adapter resolves Version+ChannelGroup to a release image pullspec.
type ReleaseSpec struct {
	// version is the OpenShift version to install.
	// Specified as semver v2 major, minor, patch without leading "v". (e.g., "4.14.9")
	//

	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:XValidation:rule="self.matches('^[a-z]+-[a-z]+[0-9]+$')",message="Version must be a valid semver v2 major.minor.patch. (e.g., 4.14.9)"
	// +example="4.14.9"
	Version string `json:"version"`

	// TODO: Description, validation and examples.

	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=63
	ChannelGroup string `json:"channelGroup"`
}

type NetworkingSpec struct {
	// machineNetwork is the list of IP address pools for machines.
	// This might be used among other things to generate appropriate networking security groups in some clouds providers.
	// Currently only one entry or two for dual stack is supported.
	// This field is immutable.
	//

	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="machineNetwork is immutable and cannot be modified once set."
	// +kubebuilder:validation:MaxItems=2
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:ListType=atomic
	// +optional
	// +listType=atomic
	MachineNetwork []MachineNetworkEntry `json:"machineNetwork,omitempty"`

	// clusterNetwork is the list of IP address pools for pods.
	// Defaults to cidr: "10.132.0.0/14".
	// Currently only one entry is supported.
	// This field is immutable.
	//

	// +kubebuilder:default:={{cidr: "10.132.0.0/14"}}
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="clusterNetwork is immutable and cannot be modified once set."
	// +kubebuilder:validation:MaxItems=2
	// +kubebuilder:validation:MinItems=1
	// +optional
	// +listType=atomic
	ClusterNetwork []ClusterNetworkEntry `json:"clusterNetwork,omitempty"`

	// serviceNetwork is the list of IP address pools for services.
	// Defaults to cidr: "172.31.0.0/16".
	// Currently only one entry is supported.
	// This field is immutable.
	//

	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="serviceNetwork is immutable and cannot be modified once set."
	// +kubebuilder:validation:MaxItems=1
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:default:={{cidr: "172.31.0.0/16"}}
	// +optional
	// +listType=atomic
	ServiceNetwork []string `json:"serviceNetwork,omitempty"`

	// networkType specifies the SDN provider used for cluster networking.
	// Defaults to OVNKubernetes.
	// This field is required and immutable.
	// TODO: Do we (GCP) even support other types? Can we drop this field?
	//

	// +kubebuilder:validation:XValidation:rule="self == oldSelf", message="networkType is immutable"
	// +kubebuilder:validation:Enum=OVNKubernetes;Other
	// +optional
	// +default="OVNKubernetes"
	NetworkType string `json:"networkType,omitempty"`
}

type MachineNetworkEntry struct {
	// cidr is the IP block address pool for machines within the cluster.

	// +required
	// +kubebuilder:validation:MaxLength=43
	// +kubebuilder:validation:XValidation:rule=`self.matches('^((\\d{1,3}\\.){3}\\d{1,3}/\\d{1,2})$') || self.matches('^([0-9a-fA-F]{0,4}:){2,7}([0-9a-fA-F]{0,4})?/[0-9]{1,3}$')`,message="cidr must be a valid IPv4 or IPv6 CIDR notation (e.g., 192.168.1.0/24 or 2001:db8::/64)"
	CIDR string `json:"cidr"`
}

type ClusterNetworkEntry struct {
	// cidr is the IP block address pool for the cluster itself.

	// +required
	// +kubebuilder:validation:MaxLength=43
	// +kubebuilder:validation:XValidation:rule=`self.matches('^((\\d{1,3}\\.){3}\\d{1,3}/\\d{1,2})$') || self.matches('^([0-9a-fA-F]{0,4}:){2,7}([0-9a-fA-F]{0,4})?/[0-9]{1,3}$')`,message="cidr must be a valid IPv4 or IPv6 CIDR notation (e.g., 192.168.1.0/24 or 2001:db8::/64)"
	CIDR string `json:"cidr,omitempty"`

	// TODO: Clarify for GCP.
	// hostPrefix is the prefix size to allocate to each node from the CIDR.
	// For example, 24 would allocate 2^(32-24)=2^8=256 addresses to each node. If this
	// field is not used by the plugin, it can be left unset.
	//

	// +optional
	HostPrefix int32 `json:"hostPrefix,omitempty"`
}

// DNSSpec specifies the DNS configuration for the cluster ingress.
type DNSSpec struct {
	// baseDomain is the base domain of the cluster.
	// It will be used to configure ingress in the cluster through the subdomain baseDomainPrefix.baseDomain.
	// If baseDomainPrefix is omitted, the Cluster.name will be used as the subdomain.
	// Once set, this field is immutable.
	// When the value is the empty string "", the controller might default to a value depending on the platform.
	//

	// +kubebuilder:validation:XValidation:rule=`self == "" || self.matches('^(?:(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,}|[a-zA-Z0-9-]+)$')`,message="baseDomain must be a valid domain name (e.g., example, example.com, sub.example.com)"
	// +kubebuilder:validation:XValidation:rule=`oldSelf == "" || self == oldSelf`, message="baseDomain is immutable"
	// +kubebuilder:validation:MaxLength=253
	// +immutable
	// +required
	BaseDomain string `json:"baseDomain,omitempty"`
}

// ClusterStatus is written by controllers only.
type ClusterStatus struct {

	// +optional
	// +listType=map
	// +listMapKey=type
	// +patchStrategy=merge
	// +patchMergeKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// HostedClusterResult is written by the hc-adapter.

	// +optional
	HostedClusterResult *HostedClusterResult `json:"hostedClusterResult,omitempty"`
}

// HostedClusterResult holds the hc-adapter's output from ManifestWork status feedback.
// This field is read-only — populated by the hc-adapter only.
type HostedClusterResult struct {

	// +optional
	APIEndpoint string `json:"apiEndpoint,omitempty"`

	// +optional
	Version string `json:"version,omitempty"`
}

func init() { register(&Cluster{}, &ClusterList{}) }
