// Code generated by orlop-gen. DO NOT EDIT.

package v1

import (
	_ "embed"

	"github.com/openshift-online/gecko/orlop/pkg/apiserver/types"
)

var (
	// ChannelSchemaYAML contains the OpenAPI v3 schema for Channel.
	//go:embed .schemas/channel_schema.yaml
	ChannelSchemaYAML string

	// ClusterSchemaYAML contains the OpenAPI v3 schema for Cluster.
	//go:embed .schemas/cluster_schema.yaml
	ClusterSchemaYAML string

	// ControlPlaneUpgradePolicySchemaYAML contains the OpenAPI v3 schema for ControlPlaneUpgradePolicy.
	//go:embed .schemas/controlplaneupgradepolicy_schema.yaml
	ControlPlaneUpgradePolicySchemaYAML string

	// NodePoolSchemaYAML contains the OpenAPI v3 schema for NodePool.
	//go:embed .schemas/nodepool_schema.yaml
	NodePoolSchemaYAML string

	// RoleBindingSchemaYAML contains the OpenAPI v3 schema for RoleBinding.
	//go:embed .schemas/rolebinding_schema.yaml
	RoleBindingSchemaYAML string

	// RoleSchemaYAML contains the OpenAPI v3 schema for Role.
	//go:embed .schemas/role_schema.yaml
	RoleSchemaYAML string

	// VersionSchemaYAML contains the OpenAPI v3 schema for Version.
	//go:embed .schemas/version_schema.yaml
	VersionSchemaYAML string

)

// ChannelResourceInfo describes the Channel resource type.
var ChannelResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("Channel"),
	Plural:     "channels",
	Singular:   "channel",
	Namespaced: false,
	SchemaYAML: ChannelSchemaYAML,
	// Generated from // +orlop:public-verbs annotation.
	Verbs: []string{"get", "list"},
	// Generated from // +orlop:authorization-policy annotation.
	AuthorizationPolicyRefs: map[string]string{
		"get": "authenticated-catalog-read",
		"list": "authenticated-catalog-read",
	},
}

// ClusterResourceInfo describes the Cluster resource type.
var ClusterResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("Cluster"),
	Plural:     "clusters",
	Singular:   "cluster",
	Namespaced: true,
	SchemaYAML: ClusterSchemaYAML,
	PrinterColumns: []types.PrinterColumn{
		{
			Name:        "Available",
			Type:        "string",
			JSONPath:    ".status.conditions[?(@.type==\"HostedClusterAvailable\")].status",
		},
		{
			Name:        "Age",
			Type:        "date",
			JSONPath:    ".metadata.creationTimestamp",
		},
	},
}

// ControlPlaneUpgradePolicyResourceInfo describes the ControlPlaneUpgradePolicy resource type.
var ControlPlaneUpgradePolicyResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("ControlPlaneUpgradePolicy"),
	Plural:     "controlplaneupgradepolicies",
	Singular:   "controlplaneupgradepolicy",
	Namespaced: true,
	SchemaYAML: ControlPlaneUpgradePolicySchemaYAML,
}

// NodePoolResourceInfo describes the NodePool resource type.
var NodePoolResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("NodePool"),
	Plural:     "nodepools",
	Singular:   "nodepool",
	Namespaced: true,
	SchemaYAML: NodePoolSchemaYAML,
	PrinterColumns: []types.PrinterColumn{
		{
			Name:        "Available",
			Type:        "string",
			JSONPath:    ".status.conditions[?(@.type==\"NodePoolAvailable\")].status",
		},
		{
			Name:        "Healthy",
			Type:        "string",
			JSONPath:    ".status.conditions[?(@.type==\"NodePoolHealthy\")].status",
		},
		{
			Name:        "Progressing",
			Type:        "string",
			JSONPath:    ".status.conditions[?(@.type==\"NodePoolProgressing\")].status",
		},
		{
			Name:        "Age",
			Type:        "date",
			JSONPath:    ".metadata.creationTimestamp",
		},
	},
}

// RoleBindingResourceInfo describes the RoleBinding resource type.
var RoleBindingResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("RoleBinding"),
	Plural:     "rolebindings",
	Singular:   "rolebinding",
	Namespaced: true,
	SchemaYAML: RoleBindingSchemaYAML,
}

// RoleResourceInfo describes the Role resource type.
var RoleResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("Role"),
	Plural:     "roles",
	Singular:   "role",
	Namespaced: true,
	SchemaYAML: RoleSchemaYAML,
}

// VersionResourceInfo describes the Version resource type.
var VersionResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("Version"),
	Plural:     "versions",
	Singular:   "version",
	Namespaced: false,
	SchemaYAML: VersionSchemaYAML,
	// Generated from // +orlop:public-verbs annotation.
	Verbs: []string{"get", "list"},
	// Generated from // +orlop:authorization-policy annotation.
	AuthorizationPolicyRefs: map[string]string{
		"get": "authenticated-catalog-read",
		"list": "authenticated-catalog-read",
	},
}

// GetResourceInfos returns ResourceInfo definitions for all types in this package.
// This can be used to configure an API server with these resources.
func GetResourceInfos() []types.ResourceInfo {
	return []types.ResourceInfo{
		ChannelResourceInfo,
		ClusterResourceInfo,
		ControlPlaneUpgradePolicyResourceInfo,
		NodePoolResourceInfo,
		RoleBindingResourceInfo,
		RoleResourceInfo,
		VersionResourceInfo,
	}
}
