//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by orlop-gen. DO NOT EDIT.

package v1

import (
	"encoding/json"

	privatev1 "github.com/openshift-online/gecko/platform-api/api/private/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*privatev1.AutoscalingSpec)(nil), (*AutoscalingSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_AutoscalingSpec_PrivateToPublic(a.(*privatev1.AutoscalingSpec), b.(*AutoscalingSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AutoscalingSpec)(nil), (*privatev1.AutoscalingSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_AutoscalingSpec_PublicToPrivate(a.(*AutoscalingSpec), b.(*privatev1.AutoscalingSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.Cluster)(nil), (*Cluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Cluster_PrivateToPublic(a.(*privatev1.Cluster), b.(*Cluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Cluster)(nil), (*privatev1.Cluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Cluster_PublicToPrivate(a.(*Cluster), b.(*privatev1.Cluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ClusterList)(nil), (*ClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterList_PrivateToPublic(a.(*privatev1.ClusterList), b.(*ClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterList)(nil), (*privatev1.ClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterList_PublicToPrivate(a.(*ClusterList), b.(*privatev1.ClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ClusterNetworkEntry)(nil), (*ClusterNetworkEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterNetworkEntry_PrivateToPublic(a.(*privatev1.ClusterNetworkEntry), b.(*ClusterNetworkEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterNetworkEntry)(nil), (*privatev1.ClusterNetworkEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterNetworkEntry_PublicToPrivate(a.(*ClusterNetworkEntry), b.(*privatev1.ClusterNetworkEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ClusterPlatformSpec)(nil), (*ClusterPlatformSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterPlatformSpec_PrivateToPublic(a.(*privatev1.ClusterPlatformSpec), b.(*ClusterPlatformSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterPlatformSpec)(nil), (*privatev1.ClusterPlatformSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterPlatformSpec_PublicToPrivate(a.(*ClusterPlatformSpec), b.(*privatev1.ClusterPlatformSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ClusterSpec)(nil), (*ClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterSpec_PrivateToPublic(a.(*privatev1.ClusterSpec), b.(*ClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterSpec)(nil), (*privatev1.ClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterSpec_PublicToPrivate(a.(*ClusterSpec), b.(*privatev1.ClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ClusterStatus)(nil), (*ClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterStatus_PrivateToPublic(a.(*privatev1.ClusterStatus), b.(*ClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterStatus)(nil), (*privatev1.ClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterStatus_PublicToPrivate(a.(*ClusterStatus), b.(*privatev1.ClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.DNSSpec)(nil), (*DNSSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_DNSSpec_PrivateToPublic(a.(*privatev1.DNSSpec), b.(*DNSSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DNSSpec)(nil), (*privatev1.DNSSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_DNSSpec_PublicToPrivate(a.(*DNSSpec), b.(*privatev1.DNSSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.GCPClusterPlatform)(nil), (*GCPClusterPlatform)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_GCPClusterPlatform_PrivateToPublic(a.(*privatev1.GCPClusterPlatform), b.(*GCPClusterPlatform), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GCPClusterPlatform)(nil), (*privatev1.GCPClusterPlatform)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_GCPClusterPlatform_PublicToPrivate(a.(*GCPClusterPlatform), b.(*privatev1.GCPClusterPlatform), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.GCPNodePoolPlatform)(nil), (*GCPNodePoolPlatform)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_GCPNodePoolPlatform_PrivateToPublic(a.(*privatev1.GCPNodePoolPlatform), b.(*GCPNodePoolPlatform), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GCPNodePoolPlatform)(nil), (*privatev1.GCPNodePoolPlatform)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_GCPNodePoolPlatform_PublicToPrivate(a.(*GCPNodePoolPlatform), b.(*privatev1.GCPNodePoolPlatform), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.GCPResourceLabel)(nil), (*GCPResourceLabel)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_GCPResourceLabel_PrivateToPublic(a.(*privatev1.GCPResourceLabel), b.(*GCPResourceLabel), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GCPResourceLabel)(nil), (*privatev1.GCPResourceLabel)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_GCPResourceLabel_PublicToPrivate(a.(*GCPResourceLabel), b.(*privatev1.GCPResourceLabel), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.HostedClusterResult)(nil), (*HostedClusterResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_HostedClusterResult_PrivateToPublic(a.(*privatev1.HostedClusterResult), b.(*HostedClusterResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostedClusterResult)(nil), (*privatev1.HostedClusterResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_HostedClusterResult_PublicToPrivate(a.(*HostedClusterResult), b.(*privatev1.HostedClusterResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.MachineNetworkEntry)(nil), (*MachineNetworkEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_MachineNetworkEntry_PrivateToPublic(a.(*privatev1.MachineNetworkEntry), b.(*MachineNetworkEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineNetworkEntry)(nil), (*privatev1.MachineNetworkEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_MachineNetworkEntry_PublicToPrivate(a.(*MachineNetworkEntry), b.(*privatev1.MachineNetworkEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.NetworkingSpec)(nil), (*NetworkingSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NetworkingSpec_PrivateToPublic(a.(*privatev1.NetworkingSpec), b.(*NetworkingSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkingSpec)(nil), (*privatev1.NetworkingSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NetworkingSpec_PublicToPrivate(a.(*NetworkingSpec), b.(*privatev1.NetworkingSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.NodePool)(nil), (*NodePool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePool_PrivateToPublic(a.(*privatev1.NodePool), b.(*NodePool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodePool)(nil), (*privatev1.NodePool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePool_PublicToPrivate(a.(*NodePool), b.(*privatev1.NodePool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.NodePoolList)(nil), (*NodePoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePoolList_PrivateToPublic(a.(*privatev1.NodePoolList), b.(*NodePoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodePoolList)(nil), (*privatev1.NodePoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePoolList_PublicToPrivate(a.(*NodePoolList), b.(*privatev1.NodePoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.NodePoolPlatformSpec)(nil), (*NodePoolPlatformSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePoolPlatformSpec_PrivateToPublic(a.(*privatev1.NodePoolPlatformSpec), b.(*NodePoolPlatformSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodePoolPlatformSpec)(nil), (*privatev1.NodePoolPlatformSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePoolPlatformSpec_PublicToPrivate(a.(*NodePoolPlatformSpec), b.(*privatev1.NodePoolPlatformSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.NodePoolSpec)(nil), (*NodePoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePoolSpec_PrivateToPublic(a.(*privatev1.NodePoolSpec), b.(*NodePoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodePoolSpec)(nil), (*privatev1.NodePoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePoolSpec_PublicToPrivate(a.(*NodePoolSpec), b.(*privatev1.NodePoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.NodePoolStatus)(nil), (*NodePoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePoolStatus_PrivateToPublic(a.(*privatev1.NodePoolStatus), b.(*NodePoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodePoolStatus)(nil), (*privatev1.NodePoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePoolStatus_PublicToPrivate(a.(*NodePoolStatus), b.(*privatev1.NodePoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.PlatformRole)(nil), (*PlatformRole)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_PlatformRole_PrivateToPublic(a.(*privatev1.PlatformRole), b.(*PlatformRole), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlatformRole)(nil), (*privatev1.PlatformRole)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_PlatformRole_PublicToPrivate(a.(*PlatformRole), b.(*privatev1.PlatformRole), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.PlatformRoleList)(nil), (*PlatformRoleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_PlatformRoleList_PrivateToPublic(a.(*privatev1.PlatformRoleList), b.(*PlatformRoleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlatformRoleList)(nil), (*privatev1.PlatformRoleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_PlatformRoleList_PublicToPrivate(a.(*PlatformRoleList), b.(*privatev1.PlatformRoleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.PlatformRoleSpec)(nil), (*PlatformRoleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_PlatformRoleSpec_PrivateToPublic(a.(*privatev1.PlatformRoleSpec), b.(*PlatformRoleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlatformRoleSpec)(nil), (*privatev1.PlatformRoleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_PlatformRoleSpec_PublicToPrivate(a.(*PlatformRoleSpec), b.(*privatev1.PlatformRoleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ReleaseSpec)(nil), (*ReleaseSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ReleaseSpec_PrivateToPublic(a.(*privatev1.ReleaseSpec), b.(*ReleaseSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseSpec)(nil), (*privatev1.ReleaseSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ReleaseSpec_PublicToPrivate(a.(*ReleaseSpec), b.(*privatev1.ReleaseSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.Role)(nil), (*Role)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Role_PrivateToPublic(a.(*privatev1.Role), b.(*Role), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Role)(nil), (*privatev1.Role)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Role_PublicToPrivate(a.(*Role), b.(*privatev1.Role), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.RoleBinding)(nil), (*RoleBinding)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_RoleBinding_PrivateToPublic(a.(*privatev1.RoleBinding), b.(*RoleBinding), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RoleBinding)(nil), (*privatev1.RoleBinding)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_RoleBinding_PublicToPrivate(a.(*RoleBinding), b.(*privatev1.RoleBinding), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.RoleBindingList)(nil), (*RoleBindingList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_RoleBindingList_PrivateToPublic(a.(*privatev1.RoleBindingList), b.(*RoleBindingList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RoleBindingList)(nil), (*privatev1.RoleBindingList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_RoleBindingList_PublicToPrivate(a.(*RoleBindingList), b.(*privatev1.RoleBindingList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.RoleBindingSpec)(nil), (*RoleBindingSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_RoleBindingSpec_PrivateToPublic(a.(*privatev1.RoleBindingSpec), b.(*RoleBindingSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RoleBindingSpec)(nil), (*privatev1.RoleBindingSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_RoleBindingSpec_PublicToPrivate(a.(*RoleBindingSpec), b.(*privatev1.RoleBindingSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.RoleList)(nil), (*RoleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_RoleList_PrivateToPublic(a.(*privatev1.RoleList), b.(*RoleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RoleList)(nil), (*privatev1.RoleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_RoleList_PublicToPrivate(a.(*RoleList), b.(*privatev1.RoleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.RoleRef)(nil), (*RoleRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_RoleRef_PrivateToPublic(a.(*privatev1.RoleRef), b.(*RoleRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RoleRef)(nil), (*privatev1.RoleRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_RoleRef_PublicToPrivate(a.(*RoleRef), b.(*privatev1.RoleRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.RoleSpec)(nil), (*RoleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_RoleSpec_PrivateToPublic(a.(*privatev1.RoleSpec), b.(*RoleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RoleSpec)(nil), (*privatev1.RoleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_RoleSpec_PublicToPrivate(a.(*RoleSpec), b.(*privatev1.RoleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ServiceAccountsRef)(nil), (*ServiceAccountsRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ServiceAccountsRef_PrivateToPublic(a.(*privatev1.ServiceAccountsRef), b.(*ServiceAccountsRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceAccountsRef)(nil), (*privatev1.ServiceAccountsRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ServiceAccountsRef_PublicToPrivate(a.(*ServiceAccountsRef), b.(*privatev1.ServiceAccountsRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.TaintSpec)(nil), (*TaintSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_TaintSpec_PrivateToPublic(a.(*privatev1.TaintSpec), b.(*TaintSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TaintSpec)(nil), (*privatev1.TaintSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_TaintSpec_PublicToPrivate(a.(*TaintSpec), b.(*privatev1.TaintSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.WorkloadIdentitySpec)(nil), (*WorkloadIdentitySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_WorkloadIdentitySpec_PrivateToPublic(a.(*privatev1.WorkloadIdentitySpec), b.(*WorkloadIdentitySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkloadIdentitySpec)(nil), (*privatev1.WorkloadIdentitySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_WorkloadIdentitySpec_PublicToPrivate(a.(*WorkloadIdentitySpec), b.(*privatev1.WorkloadIdentitySpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_AutoscalingSpec_PrivateToPublic(in *privatev1.AutoscalingSpec, out *AutoscalingSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_AutoscalingSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_AutoscalingSpec_PrivateToPublic(in *privatev1.AutoscalingSpec, out *AutoscalingSpec, s conversion.Scope) error {
	return autoConvert_AutoscalingSpec_PrivateToPublic(in, out, s)
}

func autoConvert_AutoscalingSpec_PublicToPrivate(in *AutoscalingSpec, out *privatev1.AutoscalingSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_AutoscalingSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_AutoscalingSpec_PublicToPrivate(in *AutoscalingSpec, out *privatev1.AutoscalingSpec, s conversion.Scope) error {
	return autoConvert_AutoscalingSpec_PublicToPrivate(in, out, s)
}

func autoConvert_Cluster_PrivateToPublic(in *privatev1.Cluster, out *Cluster, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_Cluster_PrivateToPublic is an autogenerated conversion function.
func Convert_Cluster_PrivateToPublic(in *privatev1.Cluster, out *Cluster, s conversion.Scope) error {
	return autoConvert_Cluster_PrivateToPublic(in, out, s)
}

func autoConvert_Cluster_PublicToPrivate(in *Cluster, out *privatev1.Cluster, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_Cluster_PublicToPrivate is an autogenerated conversion function.
func Convert_Cluster_PublicToPrivate(in *Cluster, out *privatev1.Cluster, s conversion.Scope) error {
	return autoConvert_Cluster_PublicToPrivate(in, out, s)
}

func autoConvert_ClusterList_PrivateToPublic(in *privatev1.ClusterList, out *ClusterList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterList_PrivateToPublic is an autogenerated conversion function.
func Convert_ClusterList_PrivateToPublic(in *privatev1.ClusterList, out *ClusterList, s conversion.Scope) error {
	return autoConvert_ClusterList_PrivateToPublic(in, out, s)
}

func autoConvert_ClusterList_PublicToPrivate(in *ClusterList, out *privatev1.ClusterList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterList_PublicToPrivate is an autogenerated conversion function.
func Convert_ClusterList_PublicToPrivate(in *ClusterList, out *privatev1.ClusterList, s conversion.Scope) error {
	return autoConvert_ClusterList_PublicToPrivate(in, out, s)
}

func autoConvert_ClusterNetworkEntry_PrivateToPublic(in *privatev1.ClusterNetworkEntry, out *ClusterNetworkEntry, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterNetworkEntry_PrivateToPublic is an autogenerated conversion function.
func Convert_ClusterNetworkEntry_PrivateToPublic(in *privatev1.ClusterNetworkEntry, out *ClusterNetworkEntry, s conversion.Scope) error {
	return autoConvert_ClusterNetworkEntry_PrivateToPublic(in, out, s)
}

func autoConvert_ClusterNetworkEntry_PublicToPrivate(in *ClusterNetworkEntry, out *privatev1.ClusterNetworkEntry, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterNetworkEntry_PublicToPrivate is an autogenerated conversion function.
func Convert_ClusterNetworkEntry_PublicToPrivate(in *ClusterNetworkEntry, out *privatev1.ClusterNetworkEntry, s conversion.Scope) error {
	return autoConvert_ClusterNetworkEntry_PublicToPrivate(in, out, s)
}

func autoConvert_ClusterPlatformSpec_PrivateToPublic(in *privatev1.ClusterPlatformSpec, out *ClusterPlatformSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterPlatformSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_ClusterPlatformSpec_PrivateToPublic(in *privatev1.ClusterPlatformSpec, out *ClusterPlatformSpec, s conversion.Scope) error {
	return autoConvert_ClusterPlatformSpec_PrivateToPublic(in, out, s)
}

func autoConvert_ClusterPlatformSpec_PublicToPrivate(in *ClusterPlatformSpec, out *privatev1.ClusterPlatformSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterPlatformSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_ClusterPlatformSpec_PublicToPrivate(in *ClusterPlatformSpec, out *privatev1.ClusterPlatformSpec, s conversion.Scope) error {
	return autoConvert_ClusterPlatformSpec_PublicToPrivate(in, out, s)
}

func autoConvert_ClusterSpec_PrivateToPublic(in *privatev1.ClusterSpec, out *ClusterSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_ClusterSpec_PrivateToPublic(in *privatev1.ClusterSpec, out *ClusterSpec, s conversion.Scope) error {
	return autoConvert_ClusterSpec_PrivateToPublic(in, out, s)
}

func autoConvert_ClusterSpec_PublicToPrivate(in *ClusterSpec, out *privatev1.ClusterSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_ClusterSpec_PublicToPrivate(in *ClusterSpec, out *privatev1.ClusterSpec, s conversion.Scope) error {
	return autoConvert_ClusterSpec_PublicToPrivate(in, out, s)
}

func autoConvert_ClusterStatus_PrivateToPublic(in *privatev1.ClusterStatus, out *ClusterStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterStatus_PrivateToPublic is an autogenerated conversion function.
func Convert_ClusterStatus_PrivateToPublic(in *privatev1.ClusterStatus, out *ClusterStatus, s conversion.Scope) error {
	return autoConvert_ClusterStatus_PrivateToPublic(in, out, s)
}

func autoConvert_ClusterStatus_PublicToPrivate(in *ClusterStatus, out *privatev1.ClusterStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterStatus_PublicToPrivate is an autogenerated conversion function.
func Convert_ClusterStatus_PublicToPrivate(in *ClusterStatus, out *privatev1.ClusterStatus, s conversion.Scope) error {
	return autoConvert_ClusterStatus_PublicToPrivate(in, out, s)
}

func autoConvert_DNSSpec_PrivateToPublic(in *privatev1.DNSSpec, out *DNSSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_DNSSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_DNSSpec_PrivateToPublic(in *privatev1.DNSSpec, out *DNSSpec, s conversion.Scope) error {
	return autoConvert_DNSSpec_PrivateToPublic(in, out, s)
}

func autoConvert_DNSSpec_PublicToPrivate(in *DNSSpec, out *privatev1.DNSSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_DNSSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_DNSSpec_PublicToPrivate(in *DNSSpec, out *privatev1.DNSSpec, s conversion.Scope) error {
	return autoConvert_DNSSpec_PublicToPrivate(in, out, s)
}

func autoConvert_GCPClusterPlatform_PrivateToPublic(in *privatev1.GCPClusterPlatform, out *GCPClusterPlatform, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_GCPClusterPlatform_PrivateToPublic is an autogenerated conversion function.
func Convert_GCPClusterPlatform_PrivateToPublic(in *privatev1.GCPClusterPlatform, out *GCPClusterPlatform, s conversion.Scope) error {
	return autoConvert_GCPClusterPlatform_PrivateToPublic(in, out, s)
}

func autoConvert_GCPClusterPlatform_PublicToPrivate(in *GCPClusterPlatform, out *privatev1.GCPClusterPlatform, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_GCPClusterPlatform_PublicToPrivate is an autogenerated conversion function.
func Convert_GCPClusterPlatform_PublicToPrivate(in *GCPClusterPlatform, out *privatev1.GCPClusterPlatform, s conversion.Scope) error {
	return autoConvert_GCPClusterPlatform_PublicToPrivate(in, out, s)
}

func autoConvert_GCPNodePoolPlatform_PrivateToPublic(in *privatev1.GCPNodePoolPlatform, out *GCPNodePoolPlatform, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_GCPNodePoolPlatform_PrivateToPublic is an autogenerated conversion function.
func Convert_GCPNodePoolPlatform_PrivateToPublic(in *privatev1.GCPNodePoolPlatform, out *GCPNodePoolPlatform, s conversion.Scope) error {
	return autoConvert_GCPNodePoolPlatform_PrivateToPublic(in, out, s)
}

func autoConvert_GCPNodePoolPlatform_PublicToPrivate(in *GCPNodePoolPlatform, out *privatev1.GCPNodePoolPlatform, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_GCPNodePoolPlatform_PublicToPrivate is an autogenerated conversion function.
func Convert_GCPNodePoolPlatform_PublicToPrivate(in *GCPNodePoolPlatform, out *privatev1.GCPNodePoolPlatform, s conversion.Scope) error {
	return autoConvert_GCPNodePoolPlatform_PublicToPrivate(in, out, s)
}

func autoConvert_GCPResourceLabel_PrivateToPublic(in *privatev1.GCPResourceLabel, out *GCPResourceLabel, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_GCPResourceLabel_PrivateToPublic is an autogenerated conversion function.
func Convert_GCPResourceLabel_PrivateToPublic(in *privatev1.GCPResourceLabel, out *GCPResourceLabel, s conversion.Scope) error {
	return autoConvert_GCPResourceLabel_PrivateToPublic(in, out, s)
}

func autoConvert_GCPResourceLabel_PublicToPrivate(in *GCPResourceLabel, out *privatev1.GCPResourceLabel, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_GCPResourceLabel_PublicToPrivate is an autogenerated conversion function.
func Convert_GCPResourceLabel_PublicToPrivate(in *GCPResourceLabel, out *privatev1.GCPResourceLabel, s conversion.Scope) error {
	return autoConvert_GCPResourceLabel_PublicToPrivate(in, out, s)
}

func autoConvert_HostedClusterResult_PrivateToPublic(in *privatev1.HostedClusterResult, out *HostedClusterResult, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_HostedClusterResult_PrivateToPublic is an autogenerated conversion function.
func Convert_HostedClusterResult_PrivateToPublic(in *privatev1.HostedClusterResult, out *HostedClusterResult, s conversion.Scope) error {
	return autoConvert_HostedClusterResult_PrivateToPublic(in, out, s)
}

func autoConvert_HostedClusterResult_PublicToPrivate(in *HostedClusterResult, out *privatev1.HostedClusterResult, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_HostedClusterResult_PublicToPrivate is an autogenerated conversion function.
func Convert_HostedClusterResult_PublicToPrivate(in *HostedClusterResult, out *privatev1.HostedClusterResult, s conversion.Scope) error {
	return autoConvert_HostedClusterResult_PublicToPrivate(in, out, s)
}

func autoConvert_MachineNetworkEntry_PrivateToPublic(in *privatev1.MachineNetworkEntry, out *MachineNetworkEntry, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_MachineNetworkEntry_PrivateToPublic is an autogenerated conversion function.
func Convert_MachineNetworkEntry_PrivateToPublic(in *privatev1.MachineNetworkEntry, out *MachineNetworkEntry, s conversion.Scope) error {
	return autoConvert_MachineNetworkEntry_PrivateToPublic(in, out, s)
}

func autoConvert_MachineNetworkEntry_PublicToPrivate(in *MachineNetworkEntry, out *privatev1.MachineNetworkEntry, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_MachineNetworkEntry_PublicToPrivate is an autogenerated conversion function.
func Convert_MachineNetworkEntry_PublicToPrivate(in *MachineNetworkEntry, out *privatev1.MachineNetworkEntry, s conversion.Scope) error {
	return autoConvert_MachineNetworkEntry_PublicToPrivate(in, out, s)
}

func autoConvert_NetworkingSpec_PrivateToPublic(in *privatev1.NetworkingSpec, out *NetworkingSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NetworkingSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_NetworkingSpec_PrivateToPublic(in *privatev1.NetworkingSpec, out *NetworkingSpec, s conversion.Scope) error {
	return autoConvert_NetworkingSpec_PrivateToPublic(in, out, s)
}

func autoConvert_NetworkingSpec_PublicToPrivate(in *NetworkingSpec, out *privatev1.NetworkingSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NetworkingSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_NetworkingSpec_PublicToPrivate(in *NetworkingSpec, out *privatev1.NetworkingSpec, s conversion.Scope) error {
	return autoConvert_NetworkingSpec_PublicToPrivate(in, out, s)
}

func autoConvert_NodePool_PrivateToPublic(in *privatev1.NodePool, out *NodePool, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePool_PrivateToPublic is an autogenerated conversion function.
func Convert_NodePool_PrivateToPublic(in *privatev1.NodePool, out *NodePool, s conversion.Scope) error {
	return autoConvert_NodePool_PrivateToPublic(in, out, s)
}

func autoConvert_NodePool_PublicToPrivate(in *NodePool, out *privatev1.NodePool, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePool_PublicToPrivate is an autogenerated conversion function.
func Convert_NodePool_PublicToPrivate(in *NodePool, out *privatev1.NodePool, s conversion.Scope) error {
	return autoConvert_NodePool_PublicToPrivate(in, out, s)
}

func autoConvert_NodePoolList_PrivateToPublic(in *privatev1.NodePoolList, out *NodePoolList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePoolList_PrivateToPublic is an autogenerated conversion function.
func Convert_NodePoolList_PrivateToPublic(in *privatev1.NodePoolList, out *NodePoolList, s conversion.Scope) error {
	return autoConvert_NodePoolList_PrivateToPublic(in, out, s)
}

func autoConvert_NodePoolList_PublicToPrivate(in *NodePoolList, out *privatev1.NodePoolList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePoolList_PublicToPrivate is an autogenerated conversion function.
func Convert_NodePoolList_PublicToPrivate(in *NodePoolList, out *privatev1.NodePoolList, s conversion.Scope) error {
	return autoConvert_NodePoolList_PublicToPrivate(in, out, s)
}

func autoConvert_NodePoolPlatformSpec_PrivateToPublic(in *privatev1.NodePoolPlatformSpec, out *NodePoolPlatformSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePoolPlatformSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_NodePoolPlatformSpec_PrivateToPublic(in *privatev1.NodePoolPlatformSpec, out *NodePoolPlatformSpec, s conversion.Scope) error {
	return autoConvert_NodePoolPlatformSpec_PrivateToPublic(in, out, s)
}

func autoConvert_NodePoolPlatformSpec_PublicToPrivate(in *NodePoolPlatformSpec, out *privatev1.NodePoolPlatformSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePoolPlatformSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_NodePoolPlatformSpec_PublicToPrivate(in *NodePoolPlatformSpec, out *privatev1.NodePoolPlatformSpec, s conversion.Scope) error {
	return autoConvert_NodePoolPlatformSpec_PublicToPrivate(in, out, s)
}

func autoConvert_NodePoolSpec_PrivateToPublic(in *privatev1.NodePoolSpec, out *NodePoolSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePoolSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_NodePoolSpec_PrivateToPublic(in *privatev1.NodePoolSpec, out *NodePoolSpec, s conversion.Scope) error {
	return autoConvert_NodePoolSpec_PrivateToPublic(in, out, s)
}

func autoConvert_NodePoolSpec_PublicToPrivate(in *NodePoolSpec, out *privatev1.NodePoolSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePoolSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_NodePoolSpec_PublicToPrivate(in *NodePoolSpec, out *privatev1.NodePoolSpec, s conversion.Scope) error {
	return autoConvert_NodePoolSpec_PublicToPrivate(in, out, s)
}

func autoConvert_NodePoolStatus_PrivateToPublic(in *privatev1.NodePoolStatus, out *NodePoolStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePoolStatus_PrivateToPublic is an autogenerated conversion function.
func Convert_NodePoolStatus_PrivateToPublic(in *privatev1.NodePoolStatus, out *NodePoolStatus, s conversion.Scope) error {
	return autoConvert_NodePoolStatus_PrivateToPublic(in, out, s)
}

func autoConvert_NodePoolStatus_PublicToPrivate(in *NodePoolStatus, out *privatev1.NodePoolStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePoolStatus_PublicToPrivate is an autogenerated conversion function.
func Convert_NodePoolStatus_PublicToPrivate(in *NodePoolStatus, out *privatev1.NodePoolStatus, s conversion.Scope) error {
	return autoConvert_NodePoolStatus_PublicToPrivate(in, out, s)
}

func autoConvert_PlatformRole_PrivateToPublic(in *privatev1.PlatformRole, out *PlatformRole, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_PlatformRole_PrivateToPublic is an autogenerated conversion function.
func Convert_PlatformRole_PrivateToPublic(in *privatev1.PlatformRole, out *PlatformRole, s conversion.Scope) error {
	return autoConvert_PlatformRole_PrivateToPublic(in, out, s)
}

func autoConvert_PlatformRole_PublicToPrivate(in *PlatformRole, out *privatev1.PlatformRole, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_PlatformRole_PublicToPrivate is an autogenerated conversion function.
func Convert_PlatformRole_PublicToPrivate(in *PlatformRole, out *privatev1.PlatformRole, s conversion.Scope) error {
	return autoConvert_PlatformRole_PublicToPrivate(in, out, s)
}

func autoConvert_PlatformRoleList_PrivateToPublic(in *privatev1.PlatformRoleList, out *PlatformRoleList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_PlatformRoleList_PrivateToPublic is an autogenerated conversion function.
func Convert_PlatformRoleList_PrivateToPublic(in *privatev1.PlatformRoleList, out *PlatformRoleList, s conversion.Scope) error {
	return autoConvert_PlatformRoleList_PrivateToPublic(in, out, s)
}

func autoConvert_PlatformRoleList_PublicToPrivate(in *PlatformRoleList, out *privatev1.PlatformRoleList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_PlatformRoleList_PublicToPrivate is an autogenerated conversion function.
func Convert_PlatformRoleList_PublicToPrivate(in *PlatformRoleList, out *privatev1.PlatformRoleList, s conversion.Scope) error {
	return autoConvert_PlatformRoleList_PublicToPrivate(in, out, s)
}

func autoConvert_PlatformRoleSpec_PrivateToPublic(in *privatev1.PlatformRoleSpec, out *PlatformRoleSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_PlatformRoleSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_PlatformRoleSpec_PrivateToPublic(in *privatev1.PlatformRoleSpec, out *PlatformRoleSpec, s conversion.Scope) error {
	return autoConvert_PlatformRoleSpec_PrivateToPublic(in, out, s)
}

func autoConvert_PlatformRoleSpec_PublicToPrivate(in *PlatformRoleSpec, out *privatev1.PlatformRoleSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_PlatformRoleSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_PlatformRoleSpec_PublicToPrivate(in *PlatformRoleSpec, out *privatev1.PlatformRoleSpec, s conversion.Scope) error {
	return autoConvert_PlatformRoleSpec_PublicToPrivate(in, out, s)
}

func autoConvert_ReleaseSpec_PrivateToPublic(in *privatev1.ReleaseSpec, out *ReleaseSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ReleaseSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_ReleaseSpec_PrivateToPublic(in *privatev1.ReleaseSpec, out *ReleaseSpec, s conversion.Scope) error {
	return autoConvert_ReleaseSpec_PrivateToPublic(in, out, s)
}

func autoConvert_ReleaseSpec_PublicToPrivate(in *ReleaseSpec, out *privatev1.ReleaseSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ReleaseSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_ReleaseSpec_PublicToPrivate(in *ReleaseSpec, out *privatev1.ReleaseSpec, s conversion.Scope) error {
	return autoConvert_ReleaseSpec_PublicToPrivate(in, out, s)
}

func autoConvert_Role_PrivateToPublic(in *privatev1.Role, out *Role, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_Role_PrivateToPublic is an autogenerated conversion function.
func Convert_Role_PrivateToPublic(in *privatev1.Role, out *Role, s conversion.Scope) error {
	return autoConvert_Role_PrivateToPublic(in, out, s)
}

func autoConvert_Role_PublicToPrivate(in *Role, out *privatev1.Role, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_Role_PublicToPrivate is an autogenerated conversion function.
func Convert_Role_PublicToPrivate(in *Role, out *privatev1.Role, s conversion.Scope) error {
	return autoConvert_Role_PublicToPrivate(in, out, s)
}

func autoConvert_RoleBinding_PrivateToPublic(in *privatev1.RoleBinding, out *RoleBinding, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_RoleBinding_PrivateToPublic is an autogenerated conversion function.
func Convert_RoleBinding_PrivateToPublic(in *privatev1.RoleBinding, out *RoleBinding, s conversion.Scope) error {
	return autoConvert_RoleBinding_PrivateToPublic(in, out, s)
}

func autoConvert_RoleBinding_PublicToPrivate(in *RoleBinding, out *privatev1.RoleBinding, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_RoleBinding_PublicToPrivate is an autogenerated conversion function.
func Convert_RoleBinding_PublicToPrivate(in *RoleBinding, out *privatev1.RoleBinding, s conversion.Scope) error {
	return autoConvert_RoleBinding_PublicToPrivate(in, out, s)
}

func autoConvert_RoleBindingList_PrivateToPublic(in *privatev1.RoleBindingList, out *RoleBindingList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_RoleBindingList_PrivateToPublic is an autogenerated conversion function.
func Convert_RoleBindingList_PrivateToPublic(in *privatev1.RoleBindingList, out *RoleBindingList, s conversion.Scope) error {
	return autoConvert_RoleBindingList_PrivateToPublic(in, out, s)
}

func autoConvert_RoleBindingList_PublicToPrivate(in *RoleBindingList, out *privatev1.RoleBindingList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_RoleBindingList_PublicToPrivate is an autogenerated conversion function.
func Convert_RoleBindingList_PublicToPrivate(in *RoleBindingList, out *privatev1.RoleBindingList, s conversion.Scope) error {
	return autoConvert_RoleBindingList_PublicToPrivate(in, out, s)
}

func autoConvert_RoleBindingSpec_PrivateToPublic(in *privatev1.RoleBindingSpec, out *RoleBindingSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_RoleBindingSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_RoleBindingSpec_PrivateToPublic(in *privatev1.RoleBindingSpec, out *RoleBindingSpec, s conversion.Scope) error {
	return autoConvert_RoleBindingSpec_PrivateToPublic(in, out, s)
}

func autoConvert_RoleBindingSpec_PublicToPrivate(in *RoleBindingSpec, out *privatev1.RoleBindingSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_RoleBindingSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_RoleBindingSpec_PublicToPrivate(in *RoleBindingSpec, out *privatev1.RoleBindingSpec, s conversion.Scope) error {
	return autoConvert_RoleBindingSpec_PublicToPrivate(in, out, s)
}

func autoConvert_RoleList_PrivateToPublic(in *privatev1.RoleList, out *RoleList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_RoleList_PrivateToPublic is an autogenerated conversion function.
func Convert_RoleList_PrivateToPublic(in *privatev1.RoleList, out *RoleList, s conversion.Scope) error {
	return autoConvert_RoleList_PrivateToPublic(in, out, s)
}

func autoConvert_RoleList_PublicToPrivate(in *RoleList, out *privatev1.RoleList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_RoleList_PublicToPrivate is an autogenerated conversion function.
func Convert_RoleList_PublicToPrivate(in *RoleList, out *privatev1.RoleList, s conversion.Scope) error {
	return autoConvert_RoleList_PublicToPrivate(in, out, s)
}

func autoConvert_RoleRef_PrivateToPublic(in *privatev1.RoleRef, out *RoleRef, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_RoleRef_PrivateToPublic is an autogenerated conversion function.
func Convert_RoleRef_PrivateToPublic(in *privatev1.RoleRef, out *RoleRef, s conversion.Scope) error {
	return autoConvert_RoleRef_PrivateToPublic(in, out, s)
}

func autoConvert_RoleRef_PublicToPrivate(in *RoleRef, out *privatev1.RoleRef, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_RoleRef_PublicToPrivate is an autogenerated conversion function.
func Convert_RoleRef_PublicToPrivate(in *RoleRef, out *privatev1.RoleRef, s conversion.Scope) error {
	return autoConvert_RoleRef_PublicToPrivate(in, out, s)
}

func autoConvert_RoleSpec_PrivateToPublic(in *privatev1.RoleSpec, out *RoleSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_RoleSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_RoleSpec_PrivateToPublic(in *privatev1.RoleSpec, out *RoleSpec, s conversion.Scope) error {
	return autoConvert_RoleSpec_PrivateToPublic(in, out, s)
}

func autoConvert_RoleSpec_PublicToPrivate(in *RoleSpec, out *privatev1.RoleSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_RoleSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_RoleSpec_PublicToPrivate(in *RoleSpec, out *privatev1.RoleSpec, s conversion.Scope) error {
	return autoConvert_RoleSpec_PublicToPrivate(in, out, s)
}

func autoConvert_ServiceAccountsRef_PrivateToPublic(in *privatev1.ServiceAccountsRef, out *ServiceAccountsRef, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ServiceAccountsRef_PrivateToPublic is an autogenerated conversion function.
func Convert_ServiceAccountsRef_PrivateToPublic(in *privatev1.ServiceAccountsRef, out *ServiceAccountsRef, s conversion.Scope) error {
	return autoConvert_ServiceAccountsRef_PrivateToPublic(in, out, s)
}

func autoConvert_ServiceAccountsRef_PublicToPrivate(in *ServiceAccountsRef, out *privatev1.ServiceAccountsRef, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ServiceAccountsRef_PublicToPrivate is an autogenerated conversion function.
func Convert_ServiceAccountsRef_PublicToPrivate(in *ServiceAccountsRef, out *privatev1.ServiceAccountsRef, s conversion.Scope) error {
	return autoConvert_ServiceAccountsRef_PublicToPrivate(in, out, s)
}

func autoConvert_TaintSpec_PrivateToPublic(in *privatev1.TaintSpec, out *TaintSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_TaintSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_TaintSpec_PrivateToPublic(in *privatev1.TaintSpec, out *TaintSpec, s conversion.Scope) error {
	return autoConvert_TaintSpec_PrivateToPublic(in, out, s)
}

func autoConvert_TaintSpec_PublicToPrivate(in *TaintSpec, out *privatev1.TaintSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_TaintSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_TaintSpec_PublicToPrivate(in *TaintSpec, out *privatev1.TaintSpec, s conversion.Scope) error {
	return autoConvert_TaintSpec_PublicToPrivate(in, out, s)
}

func autoConvert_WorkloadIdentitySpec_PrivateToPublic(in *privatev1.WorkloadIdentitySpec, out *WorkloadIdentitySpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_WorkloadIdentitySpec_PrivateToPublic is an autogenerated conversion function.
func Convert_WorkloadIdentitySpec_PrivateToPublic(in *privatev1.WorkloadIdentitySpec, out *WorkloadIdentitySpec, s conversion.Scope) error {
	return autoConvert_WorkloadIdentitySpec_PrivateToPublic(in, out, s)
}

func autoConvert_WorkloadIdentitySpec_PublicToPrivate(in *WorkloadIdentitySpec, out *privatev1.WorkloadIdentitySpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_WorkloadIdentitySpec_PublicToPrivate is an autogenerated conversion function.
func Convert_WorkloadIdentitySpec_PublicToPrivate(in *WorkloadIdentitySpec, out *privatev1.WorkloadIdentitySpec, s conversion.Scope) error {
	return autoConvert_WorkloadIdentitySpec_PublicToPrivate(in, out, s)
}
