// Code generated by orlop-gen. DO NOT EDIT.

package v1

import (
	_ "embed"

	"github.com/openshift-online/gecko/orlop/pkg/apiserver/types"
)

var (
	// ClusterSchemaYAML contains the OpenAPI v3 schema for Cluster.
	//go:embed .schemas/cluster_schema.yaml
	ClusterSchemaYAML string

	// NodePoolSchemaYAML contains the OpenAPI v3 schema for NodePool.
	//go:embed .schemas/nodepool_schema.yaml
	NodePoolSchemaYAML string

	// PlatformRoleSchemaYAML contains the OpenAPI v3 schema for PlatformRole.
	//go:embed .schemas/platformrole_schema.yaml
	PlatformRoleSchemaYAML string

	// RoleBindingSchemaYAML contains the OpenAPI v3 schema for RoleBinding.
	//go:embed .schemas/rolebinding_schema.yaml
	RoleBindingSchemaYAML string

	// RoleSchemaYAML contains the OpenAPI v3 schema for Role.
	//go:embed .schemas/role_schema.yaml
	RoleSchemaYAML string

)

// ClusterResourceInfo describes the Cluster resource type.
var ClusterResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("Cluster"),
	Plural:     "clusters",
	Singular:   "cluster",
	Namespaced: true,
	SchemaYAML: ClusterSchemaYAML,
	PrinterColumns: []types.PrinterColumn{
		{
			Name:        "Available",
			Type:        "string",
			JSONPath:    ".status.conditions[?(@.type==\"HostedClusterAvailable\")].status",
		},
		{
			Name:        "Age",
			Type:        "date",
			JSONPath:    ".metadata.creationTimestamp",
		},
	},
}

// NodePoolResourceInfo describes the NodePool resource type.
var NodePoolResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("NodePool"),
	Plural:     "nodepools",
	Singular:   "nodepool",
	Namespaced: true,
	SchemaYAML: NodePoolSchemaYAML,
	PrinterColumns: []types.PrinterColumn{
		{
			Name:        "Available",
			Type:        "string",
			JSONPath:    ".status.conditions[?(@.type==\"NodePoolAvailable\")].status",
		},
		{
			Name:        "Healthy",
			Type:        "string",
			JSONPath:    ".status.conditions[?(@.type==\"NodePoolHealthy\")].status",
		},
		{
			Name:        "Progressing",
			Type:        "string",
			JSONPath:    ".status.conditions[?(@.type==\"NodePoolProgressing\")].status",
		},
		{
			Name:        "Age",
			Type:        "date",
			JSONPath:    ".metadata.creationTimestamp",
		},
	},
}

// PlatformRoleResourceInfo describes the PlatformRole resource type.
var PlatformRoleResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("PlatformRole"),
	Plural:     "platformroles",
	Singular:   "platformrole",
	Namespaced: false,
	SchemaYAML: PlatformRoleSchemaYAML,
}

// RoleBindingResourceInfo describes the RoleBinding resource type.
var RoleBindingResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("RoleBinding"),
	Plural:     "rolebindings",
	Singular:   "rolebinding",
	Namespaced: true,
	SchemaYAML: RoleBindingSchemaYAML,
}

// RoleResourceInfo describes the Role resource type.
var RoleResourceInfo = types.ResourceInfo{
	GVK:        GroupVersion.WithKind("Role"),
	Plural:     "roles",
	Singular:   "role",
	Namespaced: true,
	SchemaYAML: RoleSchemaYAML,
}

// GetResourceInfos returns ResourceInfo definitions for all types in this package.
// This can be used to configure an API server with these resources.
func GetResourceInfos() []types.ResourceInfo {
	return []types.ResourceInfo{
		ClusterResourceInfo,
		NodePoolResourceInfo,
		PlatformRoleResourceInfo,
		RoleBindingResourceInfo,
		RoleResourceInfo,
	}
}
