{{- if .Values.platformRoles.enabled }}
apiVersion: gcp.managed.openshift.io/v1
kind: PlatformRole
metadata:
  name: service-admin
  labels:
    {{- include "platform-api-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: platform-role
spec:
  permissions:
    - rolebinding.create
    - rolebinding.list
    - rolebinding.get
    - rolebinding.update
    - rolebinding.delete
    - role.create
    - role.list
    - role.get
    - role.update
    - role.delete
  system: true
{{- end }}
