{{- if .Values.platformRoles.enabled }}
apiVersion: gcp.managed.openshift.io/v1
kind: PlatformRole
metadata:
  name: cluster-admin
  annotations:
    # PlatformRole is served by the platform-api-server aggregated API.
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  permissions:
    - cluster.create
    - cluster.list
    - cluster.get
    - cluster.update
    - cluster.delete
    - nodepool.create
    - nodepool.list
    - nodepool.get
    - nodepool.update
    - nodepool.delete
    - controlplaneupgradepolicy.create
    - controlplaneupgradepolicy.list
    - controlplaneupgradepolicy.get
    - controlplaneupgradepolicy.update
    - controlplaneupgradepolicy.delete
    - controlplaneupgraderequest.create
    - controlplaneupgraderequest.list
    - controlplaneupgraderequest.get
{{- end }}
