{{- include "gecko-version-resolution.validateValues" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gecko-version-resolution.fullname" . }}
  labels:
    {{- include "gecko-version-resolution.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "gecko-version-resolution.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gecko-version-resolution.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gecko-version-resolution.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: version-resolution
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - version-resolution
            {{- if .Values.orlopURL }}
            - --orlop-url={{ .Values.orlopURL }}
            {{- end }}
            - --log-level={{ .Values.logLevel }}
            - --log-format={{ .Values.logFormat }}
            - --workers={{ .Values.workers }}
            - --default-version={{ .Values.defaultVersion }}
            - --minimum-supported-version={{ .Values.minimumSupportedVersion }}
            - --cincinnati-url={{ .Values.cincinnati.url }}
            - --arch={{ .Values.cincinnati.arch }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
