apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: platform-api-server
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: platform-api-server
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8080
