{{- if and .Values.gateway.enabled (or .Values.gateway.connectionDraining.enabled .Values.gateway.cloudArmor.enabled) }}
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: {{ include "platform-api-server.fullname" . }}-backend-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform-api-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-backend-policy
spec:
  default:
    {{- if .Values.gateway.connectionDraining.enabled }}
    connectionDraining:
      drainingTimeoutSec: {{ .Values.gateway.connectionDraining.drainingTimeoutSec }}
    {{- end }}
    {{- if .Values.gateway.cloudArmor.enabled }}
    securityPolicy: {{ include "platform-api-server.fullname" . }}-cloud-armor
    {{- end }}
  targetRef:
    group: ""
    kind: Service
    name: {{ .Values.gateway.service.name }}
{{- end }}
