apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-api-server.fullname" . }}
  labels:
    {{- include "platform-api-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    {{- if and .Values.publicApi.enabled (not .Values.esp.enabled) }}
    - port: {{ .Values.publicApi.port }}
      targetPort: public-api
      protocol: TCP
      name: public-api
    {{- end }}
  selector:
    {{- include "platform-api-server.selectorLabels" . | nindent 4 }}
