package generator

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

// generateConversions generates conversion functions between private (input)
// and public (output) API types.
//
// Instead of using k8s.io/code-generator/conversion-gen, which cannot produce
// unique function names when both packages share the same version directory
// (e.g., both are "v1"), this generator produces conversion functions directly.
// Each function is named with a directional suffix (_PrivateToPublic or
// _PublicToPrivate) to guarantee uniqueness, eliminating the fragile
// post-processing that conversion-gen would require.
func (g *Generator) generateConversions() error {
	// Clean up stale artifacts from the previous conversion-gen approach.
	if err := g.cleanStaleConversionArtifacts(); err != nil {
		return fmt.Errorf("cleaning stale conversion artifacts: %w", err)
	}

	// Walk the output directory to find versioned packages with generated types.
	return filepath.Walk(g.outputDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || !info.IsDir() {
			return err
		}

		// Collect struct type names from generated files in this package.
		typeNames, err := g.collectPackageTypes(path)
		if err != nil {
			return fmt.Errorf("collecting types from %s: %w", path, err)
		}
		if len(typeNames) == 0 {
			return nil
		}

		// Determine the relative path from the output root to this package.
		relPath, err := filepath.Rel(g.outputDir, path)
		if err != nil {
			return err
		}

		// Ensure the corresponding input (private) package exists.
		privatePkgDir := filepath.Join(g.inputDir, relPath)
		if _, err := os.Stat(privatePkgDir); os.IsNotExist(err) {
			return nil
		}

		publicImportPath := g.outputBasePath + "/" + strings.ReplaceAll(relPath, string(filepath.Separator), "/")
		privateImportPath := g.inputBasePath + "/" + strings.ReplaceAll(relPath, string(filepath.Separator), "/")

		pkgName, err := determinePackageName(path)
		if err != nil {
			return fmt.Errorf("determining package name: %w", err)
		}

		fmt.Printf("  Generating conversions for %s (%d types)...\n", publicImportPath, len(typeNames))

		return g.writeConversionFile(path, pkgName, privateImportPath, typeNames)
	})
}

// collectPackageTypes parses generated Go files in a package directory and
// returns the names of top-level struct types found. It skips infrastructure
// files like deepcopy, schemas, conversion, and groupversion_info.
func (g *Generator) collectPackageTypes(pkgDir string) ([]string, error) {
	entries, err := os.ReadDir(pkgDir)
	if err != nil {
		return nil, err
	}

	var typeNames []string
	seen := make(map[string]bool)

	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") {
			continue
		}

		// Only look at generated type files; skip infrastructure.
		if !strings.HasPrefix(name, "zz_generated.") {
			continue
		}
		switch name {
		case "zz_generated.deepcopy.go",
			"zz_generated.schemas.go",
			"zz_generated.conversion.go",
			"zz_generated.groupversion_info.go":
			continue
		}

		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, filepath.Join(pkgDir, name), nil, 0)
		if err != nil {
			return nil, fmt.Errorf("parsing %s: %w", name, err)
		}

		for _, decl := range f.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				if _, ok := typeSpec.Type.(*ast.StructType); ok {
					if !seen[typeSpec.Name.Name] {
						seen[typeSpec.Name.Name] = true
						typeNames = append(typeNames, typeSpec.Name.Name)
					}
				}
			}
		}
	}

	sort.Strings(typeNames)
	return typeNames, nil
}

// conversionData holds the template variables for zz_generated.conversion.go.
type conversionData struct {
	Boilerplate       string
	PackageName       string
	PrivateImportPath string
	PrivateAlias      string // import alias for the private package
	Types             []string
}

// conversionTmpl is the template for generated conversion files.
//
// Each type gets two conversion functions with directional suffixes:
//   - Convert_<Type>_PrivateToPublic: private -> public
//   - Convert_<Type>_PublicToPrivate: public -> private
//
// The conversion uses JSON round-trip, which is consistent with the existing
// Converter implementation and correctly handles the field-subset relationship
// between public and private types.
var conversionTmpl = template.Must(template.New("conversion").Parse(`//go:build !ignore_autogenerated
// +build !ignore_autogenerated

{{ .Boilerplate }}
// Code generated by orlop-gen. DO NOT EDIT.

package {{ .PackageName }}

import (
	"encoding/json"

	{{ .PrivateAlias }} "{{ .PrivateImportPath }}"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
{{- range .Types }}
	if err := s.AddGeneratedConversionFunc((*{{ $.PrivateAlias }}.{{ . }})(nil), (*{{ . }})(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_{{ . }}_PrivateToPublic(a.(*{{ $.PrivateAlias }}.{{ . }}), b.(*{{ . }}), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*{{ . }})(nil), (*{{ $.PrivateAlias }}.{{ . }})(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_{{ . }}_PublicToPrivate(a.(*{{ . }}), b.(*{{ $.PrivateAlias }}.{{ . }}), scope)
	}); err != nil {
		return err
	}
{{- end }}
	return nil
}
{{ range .Types }}
func autoConvert_{{ . }}_PrivateToPublic(in *{{ $.PrivateAlias }}.{{ . }}, out *{{ . }}, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_{{ . }}_PrivateToPublic is an autogenerated conversion function.
func Convert_{{ . }}_PrivateToPublic(in *{{ $.PrivateAlias }}.{{ . }}, out *{{ . }}, s conversion.Scope) error {
	return autoConvert_{{ . }}_PrivateToPublic(in, out, s)
}

func autoConvert_{{ . }}_PublicToPrivate(in *{{ . }}, out *{{ $.PrivateAlias }}.{{ . }}, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_{{ . }}_PublicToPrivate is an autogenerated conversion function.
func Convert_{{ . }}_PublicToPrivate(in *{{ . }}, out *{{ $.PrivateAlias }}.{{ . }}, s conversion.Scope) error {
	return autoConvert_{{ . }}_PublicToPrivate(in, out, s)
}
{{ end -}}
`))

// writeConversionFile generates the zz_generated.conversion.go file for a
// single public package.
func (g *Generator) writeConversionFile(pkgDir, pkgName, privateImportPath string, typeNames []string) error {
	// Read boilerplate
	projectRoot := filepath.Dir(filepath.Dir(g.outputDir))
	boilerplate, err := os.ReadFile(filepath.Join(projectRoot, "hack/boilerplate.go.txt"))
	if err != nil {
		return fmt.Errorf("reading boilerplate: %w", err)
	}

	// Build a private import alias that won't collide with the current package.
	// The private and public packages typically share the same Go package name
	// (e.g., both are "v1"), so we prefix "private" to distinguish them.
	privateAlias := "private" + pkgName

	data := conversionData{
		Boilerplate:       strings.TrimSpace(string(boilerplate)),
		PackageName:       pkgName,
		PrivateImportPath: privateImportPath,
		PrivateAlias:      privateAlias,
		Types:             typeNames,
	}

	var buf strings.Builder
	if err := conversionTmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("executing template: %w", err)
	}

	outPath := filepath.Join(pkgDir, "zz_generated.conversion.go")
	return os.WriteFile(outPath, []byte(buf.String()), 0644)
}

// cleanStaleConversionArtifacts removes doc.go files from the previous
// conversion-gen approach and stale zz_generated.conversion.go files from
// packages that no longer have types (e.g., aggregator packages).
func (g *Generator) cleanStaleConversionArtifacts() error {
	return filepath.Walk(g.outputDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}

		base := filepath.Base(path)

		// Remove doc.go files that contain conversion-gen tags.
		if base == "doc.go" {
			content, err := os.ReadFile(path)
			if err != nil {
				// Unreadable doc.go — skip rather than fail the walk.
				return nil //nolint:nilerr // intentionally ignoring read error
			}
			if strings.Contains(string(content), "+k8s:conversion-gen") {
				fmt.Printf("  Removing stale %s\n", path)
				return os.Remove(path)
			}
		}

		// Remove zz_generated.conversion.go from packages without types
		// (e.g., aggregator packages that had an empty RegisterConversions).
		if base == "zz_generated.conversion.go" {
			dir := filepath.Dir(path)
			types, _ := g.collectPackageTypes(dir)

			// Also check that the corresponding private package exists.
			relPath, _ := filepath.Rel(g.outputDir, dir)
			privatePkgDir := filepath.Join(g.inputDir, relPath)
			_, privateErr := os.Stat(privatePkgDir)

			if len(types) == 0 || os.IsNotExist(privateErr) {
				fmt.Printf("  Removing stale %s\n", path)
				return os.Remove(path)
			}
		}

		return nil
	})
}
